# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_1(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(350, 360)
        Dialog.setMinimumSize(QtCore.QSize(350, 360))
        Dialog.setMaximumSize(QtCore.QSize(350, 360))
        self.pushButton_close = QtWidgets.QPushButton(Dialog)
        self.pushButton_close.setGeometry(QtCore.QRect(250, 320, 75, 23))
        self.pushButton_close.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_save = QtWidgets.QPushButton(Dialog)
        self.pushButton_save.setGeometry(QtCore.QRect(20, 320, 75, 23))
        self.pushButton_save.setObjectName("pushButton_save")
        self.date = QtWidgets.QDateEdit(Dialog)
        self.date.setGeometry(QtCore.QRect(140, 20, 181, 22))
        self.date.setObjectName("date")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.prod_name = QtWidgets.QLineEdit(Dialog)
        self.prod_name.setGeometry(QtCore.QRect(140, 52, 181, 20))
        self.prod_name.setObjectName("prod_name")
        self.Sum = QtWidgets.QLCDNumber(Dialog)
        self.Sum.setGeometry(QtCore.QRect(140, 140, 81, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Sum.setFont(font)
        self.Sum.setObjectName("Sum")
        self.count = QtWidgets.QSpinBox(Dialog)
        self.count.setGeometry(QtCore.QRect(140, 80, 91, 22))
        self.count.setMinimum(1)
        self.count.setMaximum(10000000)
        self.count.setObjectName("count")
        self.price = QtWidgets.QDoubleSpinBox(Dialog)
        self.price.setGeometry(QtCore.QRect(140, 110, 121, 22))
        self.price.setMinimum(0)
        self.price.setMaximum(10000000.0)
        self.price.setObjectName("price")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_close.setText(_translate("Dialog", "Закрыть"))
        self.label.setText(_translate("Dialog", "Дата"))
        self.label_2.setText(_translate("Dialog", "Название"))
        self.label_3.setText(_translate("Dialog", "Количество"))
        self.pushButton_save.setText(_translate("Dialog", "Сохранить"))
        self.label_4.setText(_translate("Dialog", "Цена"))
        self.label_5.setText(_translate("Dialog", "Сумма"))
