# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task_window_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_2(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(805, 642)
        MainWindow.setMinimumSize(QtCore.QSize(805, 642))
        MainWindow.setMaximumSize(QtCore.QSize(805, 642))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 621, 421))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.pushButton_close = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close.setGeometry(QtCore.QRect(700, 610, 71, 23))
        self.pushButton_close.setObjectName("pushButton_close")
        self.pushButton_add = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add.setGeometry(QtCore.QRect(30, 460, 131, 23))
        self.pushButton_add.setObjectName("pushButton_add")
        self.pushButton_mat = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_mat.setGeometry(QtCore.QRect(20, 610, 75, 23))
        self.pushButton_mat.setObjectName("pushButton_mat")
        self.pushButton_buh = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_buh.setGeometry(QtCore.QRect(110, 610, 75, 23))
        self.pushButton_buh.setObjectName("pushButton_buh")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Дата"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Название"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Покупатель"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Цена"))
        self.pushButton_close.setText(_translate("MainWindow", "Закрыть"))
        self.pushButton_add.setText(_translate("MainWindow", " Добавить сделку"))
        self.pushButton_mat.setText(_translate("MainWindow", "Расходники"))
        self.pushButton_buh.setText(_translate("MainWindow", "Расчёты"))
